# 设置pdf生成模式，有 0 1 2 3 4 5
# 0 代表不生成 pdf
# 1 代表使用 $pdfltex 选项的命令，在系统 RC 文件已经设置
# 2 代表使用 $ps2pdf；3 代表使用 $dvipdf；4 代表使用 $lualatex；
# 5 代表使用 $xelatex，在系统 RC 文件已经设置
$pdf_mode=5;

# 设置 pdflatex,xelatex,bibtex,biber 选项执行的命令
# %O, %S 是占位符;
# %O 代表选项，%S 代表对应命令的源文件
$latex = 'xelatex %O %S';
$pdflatex = "pdflatex -synctex=1 -interaction=nonstopmode -file-line-error %O %S";
$xelatex = "xelatex -synctex=1 -halt-on-error -interaction=nonstopmode -interaction=nonstopmode -file-line-error %O  %S";
$bibtex = "bibtex %O %S";
$biber = "biber %O %S";

# 生成后缀fls的文件，该文件包含程序读写时的文件列表，1代表开启
$recorder = 1;

# 设置pdf预览器, 需要把下面的程序路径更换为自己电脑pdf阅读器的路径
$pdf_previewer = 'start "/usr/bin/zathura" %O %S';

#编译完成后自动打开 pdf
$preview_mode = 1;


# 执行 latexmk -c 或 latexmk -C 时会清空 latex 程序生成的文件（-C 更强，会清空pdf）
# 除此之外, 可以设置额外的文件拓展，以进行清空
$clean_ext = "";

# 设置 bibtex 或 biber 的使用规则，有 0 1 1.5 2
# 0: 不使用 bibtex 或 biber； 清空的时候不会清空 .bbl 文件
# 1: 只有 bib 文件存在才使用 bibtex 或 biber；清空的时候不会清空 .bbl 文件
# 1.5: 只有 bib 文件存在才使用 bibtex 或 biber；当 bib 文件存在时会清空 bbl，否则不会清空
# 2: 有必要更新bbl文件时，运行 bibtex 或 biber，无需测试 bib 文件存在与否；清空删除 bbl
$bibtex_use = 2;

# 设置 latex 文件输出的目录
$out_dir = "Build";

# 设置预览模式，相当于 -pv 选项，在编译结束会开启预览
# $view 设置预览的文件格式
$preview_mode = 1;
$view = "pdf";

# 设置 latexmk 编译的文件，和不需要编译的文件，可以时多个
@default_files = ("main.tex");
@default_excluded_files = ();
